spring:
  application:
    name: api-gateway-zuul
  #  链路跟踪
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://192.168.111.118:9411/ # 指定了 Zipkin 服务器的地址

server:
  port: 5555
  tomcat:
    min-spare-threads: 2000
    max-threads: 5000
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.111.118:1111/eureka/,http://192.168.210.209:1111/eureka/
zuul:
  routes:
    jycj-uums-auth:
      path: /uums-auth/**
      service-id: jycj-uums-auth

log:
  path: /jycj/logs
  file: eureka-service-discovery-jycj
  level: INFO

logging:
  file: ${log.path}/${log.file}.log
