spring:
  application:
    name: api-gateway-zuul
server:
  port: 5555
  tomcat:
    min-spare-threads: 2000
    max-threads: 5000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.210.209:1111/eureka/,http://192.168.210.175:1111/eureka/
zuul:
  routes:
    jycj-uums-auth:
      path: /uums-auth/**
      service-id: jycj-uums-auth
    eureka-client:
      path: /eure-cli/**
      service-id: eureka-client

log:
  path: /jycj/logs
  file: eureka-service-discovery-jycj
  level: INFO

logging:
  file: ${log.path}/${log.file}.log
