spring:
  application:
    name: eureka-client-local

server:
  port: 8001
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.111.118:1111/eureka/

