spring:
  application:
    name: eureka-client-local

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://192.168.210.209:1111/eureka/,http://192.168.210.175:1111/eureka/

