spring:
  application:
    name: eureka-client-local

server:
  port: 8001
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.111.252:1111/eureka/

