spring:
  application:
    name: turbine-jycj
server:
  port: 8989

#eureka common
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://192.168.111.118:1111/eureka/

turbine:
  #参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分
  combine-host-port: true
  #参数指定了需要收集监控信息的服务名
  app-config: api-gateway-zuul

  #参数指定了集群名称为 default，当我们服务数量非常多的时候，可以启动多个 Turbine 服务来构建不同的聚合集群
  clusterNameExpression: "'default'"

log:
  path: D:/jycj/logs
  file: turbine-jycj
  level: INFO

logging:
  file: ${log.path}/${log.file}.log
