spring:
  application:
    name: eureka-service-discovery-jycj
server:
  port: 2222
log:
  path: D:/jycjtest
  file: eureka-service-discovery-jycj
  level: INFO
management:
  security:
    enabled: false
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/,http://127.0.0.1:2222/eureka/
logging:
  file: ${log.path}/${log.file}.log
