spring:
  application:
    name: eureka-service-discovery-jycj
server:
  port: 1111

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://192.168.111.118:1111/eureka/,http://192.168.210.209:1111/eureka/
log:
  path: /jycj/logs
  file: eureka-service-discovery-jycj
  level: INFO

logging:
  file: ${log.path}/${log.file}.log
