spring:
  application:
    name: eureka-service-discovery-jycj
server:
  port: 1111
log:
  path: /jycj/logs
  file: eureka-service-discovery-jycj
  level: INFO

eureka:
  server:
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 60000
    eviction-interval-timer-in-ms: 5000
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/,http://127.0.0.1:1111/eureka/
logging:
  file: ${log.path}/${log.file}.log
